name: Build
on: push
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Shallow Clone (depth=1)
        uses: actions/checkout@master
        with:
          fetch-depth: 1

      - uses: actions/setup-node@v1
        with:
          node-version: "12.16.1"

      - name: Install dependencies
        run: npm ci
  
      - name: Build App
        run: npm run build

      - name: Run test
        run: npm run test
